### ISSUE TITLE
As a user, when I win on the 9th tile click, I should see a message that `Winner is X`

### ISSUE THREAD

**Issue by dattupatel** [Shivani2224/Tic-Tac-Toe#5]
Currently, if Player 1 wins on 9th button click, it shows as match draw.

<img width="754" alt="Screenshot 2024-05-30 at 10 22 27 PM" src="https://github.com/Shivani2224/Tic-Tac-Toe/assets/6920655/df079c7f-dee0-479d-90fe-4fe1c4b7e115">

**Comment by dattupatel** [comment]
Also, `checkWinner` doesn't have a return value, so the condition `!checkWinner()` will always be true.

**Comment by Shivani2224** [comment]
I have corrected the code I have added "count = 0;" in enable button section is it correct?

**Comment by dattupatel** [comment]
The textarea still shows `Match Draw`

<img width="659" alt="Screenshot 2024-06-01 at 12 13 52 AM" src="https://github.com/Shivani2224/Tic-Tac-Toe/assets/6920655/5d3f781a-6860-4cf6-acb9-6caffc49a636">

**Comment by Shivani2224** [comment]
I have changed my condition from !checkWinner() to checkWinner() === false and is it correct?

**Comment by Shivani2224** [comment]
I have added return in checkwinner() is it correct?
